function shout(string)  {
  return string.toUpperCase()
function whisper(string)
  return string.toUpperCase()
function logShout(string)
  return string.toUpperCase()
function logWhisper(string)
  return string.toUpperCase()
function sayHiToGrandma(string)
  return string.toUpperCase()
